# Generated by Django 5.1.3 on 2024-11-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('loginUserName', models.IntegerField(max_length=50)),
                ('loginEmail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('jobTitle', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('time_date', models.DateTimeField()),
            ],
        ),
    ]
