# Generated by Django 5.1.3 on 2024-11-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='loginUserName',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
